In [15]:
import numpy as np

a = 10
b = np.zeros(a)
c = (2,2)
d = np.zeros(c)
e = np.zeros_like(d)

b[5] = 10

In [16]:
print(b)
print(d)
print(e)

[  0.   0.   0.   0.   0.  10.   0.   0.   0.   0.]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
